package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Hub skills (SPEC §11): one generated router per prefix family of on-demand
// skills, so a single description buys the whole family. `marketing-seo-audit`,
// `marketing-cro`, … stay hidden from Claude; a generated `marketing` skill is
// listed, and its body tells Claude which member's SKILL.md to read. Built from
// the members' own frontmatter, so it cannot go stale.

const hubMarker = "<!-- generated by skillsync: hub for on-demand skills. Regenerated on every sync; edit the members, not this file. -->"

// syncHubs writes a hub for every family large enough, removes hubs whose
// family shrank, and adds each hub to `desired` as "on".
func syncHubs(cfg *Config, state *State, byName map[string]Skill, desired map[string]string, now time.Time) {
	families := map[string][]Skill{}
	if min := *cfg.Exposure.HubMinMembers; min > 0 {
		for name, override := range desired {
			prefix, _, ok := strings.Cut(name, "-")
			if override != overrideInvocable || !ok {
				continue
			}
			families[prefix] = append(families[prefix], byName[name])
		}
		for prefix, members := range families {
			if _, taken := byName[prefix]; taken || len(members) < min {
				delete(families, prefix) // a real skill owns that name, or too small
			}
		}
	}

	var hubs []string
	for prefix, members := range families {
		sort.Slice(members, func(i, j int) bool { return members[i].Name < members[j].Name })
		path := filepath.Join(claudeGlobalDir(), prefix, "SKILL.md")
		if err := writeIfChanged(path, hubSkill(prefix, members)); err != nil {
			fmt.Fprintf(os.Stderr, "skillsync: hub %s: %v\n", prefix, err)
			continue
		}
		hubs = append(hubs, prefix)
		desired[prefix] = overrideOn
		if state.Exposure[prefix].Declared != "hub" {
			state.Exposure[prefix] = ExposureRecord{Declared: "hub", Since: now}
		}
		rec := state.Exposure[prefix]
		rec.Written = overrideOn
		state.Exposure[prefix] = rec
	}
	sort.Strings(hubs)
	for _, old := range state.Hubs {
		if !slices.Contains(hubs, old) {
			removeHub(old)
		}
	}
	state.Hubs = hubs
}

// hubSkill renders the router SKILL.md for one family.
func hubSkill(prefix string, members []Skill) []byte {
	names := make([]string, 0, len(members))
	for _, m := range members {
		names = append(names, m.Name)
	}
	sample := strings.Join(names[:min(3, len(names))], ", ")
	description := fmt.Sprintf("Router for the %d %s-* skills (%s, …). Use for any %s task none of the listed skills covers: pick the matching member below and follow its SKILL.md.",
		len(members), prefix, sample, prefix)

	var b bytes.Buffer
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n---\n%s\n\n", prefix, strconv.Quote(description), hubMarker)
	fmt.Fprintf(&b, "# %s\n\nRead the SKILL.md of the member that matches the task, then follow it.\n\n", prefix)
	fmt.Fprintf(&b, "| Skill | Description | SKILL.md |\n|---|---|---|\n")
	for _, m := range members {
		desc := strings.ReplaceAll(strings.ReplaceAll(m.Description, "|", "\\|"), "\n", " ")
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", m.Name, desc, filepath.Join(claudeGlobalDir(), m.Name, "SKILL.md"))
	}
	return b.Bytes()
}

// removeHub deletes a generated hub directory, refusing anything that does not
// carry the marker so a user skill that later took the name is left alone.
func removeHub(name string) {
	dir := filepath.Join(claudeGlobalDir(), name)
	b, err := os.ReadFile(filepath.Join(dir, "SKILL.md"))
	if err != nil || !bytes.Contains(b, []byte(hubMarker)) {
		return
	}
	os.RemoveAll(dir)
}
