package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Hub skills (SPEC §11): one generated router per prefix family of on-demand
// skills, so a single description buys the whole family. `marketing-seo-audit`,
// `marketing-cro`, … stay hidden from the model; a generated `marketing` skill
// is listed, and its body tells the model which member's SKILL.md to read.
// Built from the members' own frontmatter, so it cannot go stale.
//
// A hub is written into every tool that copies skills, with paths pointing at
// that tool's own copies, because each tool reads only its own directory.

const hubMarker = "<!-- generated by skillsync: hub for on-demand skills. Regenerated on every sync; edit the members, not this file. -->"

// hubDirs is the global skills directory of every enabled copying tool, in
// config order, deduplicated.
func hubDirs(cfg *Config) []string {
	var dirs []string
	for _, tool := range cfg.Tools {
		a, ok := adapters[tool]
		if !ok {
			continue
		}
		d, copies := a.(dirAdapter)
		if !copies {
			continue
		}
		if dir := d.global(); !slices.Contains(dirs, dir) {
			dirs = append(dirs, dir)
		}
	}
	return dirs
}

// syncHubs writes a hub for every family large enough, removes hubs whose
// family shrank, and adds each hub to `desired` as "on".
func syncHubs(cfg *Config, state *State, byName map[string]Skill, desired map[string]string, now time.Time) {
	families := map[string][]Skill{}
	if min := *cfg.Exposure.HubMinMembers; min > 0 {
		for name, override := range desired {
			prefix, _, ok := strings.Cut(name, "-")
			if override != overrideInvocable || !ok {
				continue
			}
			families[prefix] = append(families[prefix], byName[name])
		}
		for prefix, members := range families {
			if _, taken := byName[prefix]; taken || len(members) < min {
				delete(families, prefix) // a real skill owns that name, or too small
			}
		}
	}

	var hubs []string
	for prefix, members := range families {
		sort.Slice(members, func(i, j int) bool { return members[i].Name < members[j].Name })
		written := false
		for _, dir := range hubDirs(cfg) {
			path := filepath.Join(dir, prefix, "SKILL.md")
			if err := writeIfChanged(path, hubSkill(prefix, members, dir)); err != nil {
				fmt.Fprintf(os.Stderr, "skillsync: hub %s in %s: %v\n", prefix, dir, err)
				continue
			}
			written = true
		}
		if !written {
			continue
		}
		hubs = append(hubs, prefix)
		desired[prefix] = overrideOn
		if state.Exposure[prefix].Declared != "hub" {
			state.Exposure[prefix] = ExposureRecord{Declared: "hub", Since: now}
		}
		rec := state.Exposure[prefix]
		rec.Written = overrideOn
		state.Exposure[prefix] = rec
	}
	sort.Strings(hubs)
	for _, old := range state.Hubs {
		if !slices.Contains(hubs, old) {
			removeHub(cfg, old)
		}
	}
	state.Hubs = hubs
}

// hubSkill renders the router SKILL.md for one family, pointing at the copies
// in `dir` — the directory the tool reading this hub actually loads from.
func hubSkill(prefix string, members []Skill, dir string) []byte {
	names := make([]string, 0, len(members))
	for _, m := range members {
		names = append(names, m.Name)
	}
	sample := strings.Join(names[:min(3, len(names))], ", ")
	description := fmt.Sprintf("Router for the %d %s-* skills (%s, …). Use for any %s task none of the listed skills covers: pick the matching member below and follow its SKILL.md.",
		len(members), prefix, sample, prefix)

	var b bytes.Buffer
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n---\n%s\n\n", prefix, strconv.Quote(description), hubMarker)
	fmt.Fprintf(&b, "# %s\n\nRead the SKILL.md of the member that matches the task, then follow it.\n\n", prefix)
	fmt.Fprintf(&b, "| Skill | Description | SKILL.md |\n|---|---|---|\n")
	for _, m := range members {
		desc := strings.ReplaceAll(strings.ReplaceAll(m.Description, "|", "\\|"), "\n", " ")
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", m.Name, desc, filepath.Join(dir, m.Name, "SKILL.md"))
	}
	return b.Bytes()
}

// removeHub deletes a generated hub directory from every enabled tool,
// refusing anything that does not carry the marker so a user skill that later
// took the name is left alone.
func removeHub(cfg *Config, name string) {
	for _, dir := range hubDirs(cfg) {
		hub := filepath.Join(dir, name)
		b, err := os.ReadFile(filepath.Join(hub, "SKILL.md"))
		if err != nil || !bytes.Contains(b, []byte(hubMarker)) {
			continue
		}
		os.RemoveAll(hub)
	}
}
